import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/footer/Footer";
import Menu from "./components/menu/Menu";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VoloLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
    <html lang="en">
        <body className={inter.className}>
          <Menu />
          <div className="Responsive_center">
            <div className="Responsive">
              {children}
            </div>
          </div>
          <Footer />
        </body>
    </html>
    </> 
  );
}
